### ISSUE TITLE
  if learning_params["train"]["mode"] == "train": KeyError: 'train'

### ISSUE THREAD

**Issue by wjlong0318** [Rappsilber-Laboratory/xiRT#44]
We used the test data, but an error occurred.

xirt -i DSS_xisearch_fdr_CSM50percent_minimal.csv -o out_dir -x parameter_examples//xirt_params_rp.yaml -l parameter_examples//learning_params_training_cv.yaml
2023-09-27 16:20:44,270 - xirt - INFO - command line call:
2023-09-27 16:20:44,270 - xirt - INFO - xirt -i DSS_xisearch_fdr_CSM50percent_minimal.csv -o out_dir -x parameter_examples//xirt_params_rp.yaml -l parameter_examples//learning_params_training_cv.yaml
2023-09-27 16:20:44,270 - xirt - INFO - Init logging file.
2023-09-27 16:20:44,270 - xirt - INFO - Starting Time: 16:20:44
2023-09-27 16:20:44,273 - xirt - INFO - Starting xiRT.
2023-09-27 16:20:44,273 - xirt - INFO - Using xiRT version: 0+unknown
d:\anaconda3\lib\site-packages\tensorflow_addons\utils\tfa_eol_msg.py:23: UserWarning:

TensorFlow Addons (TFA) has ended development and introduction of new features.
TFA has entered a minimal maintenance and release mode until a planned end of life in May 2024.
Please modify downstream libraries to take dependencies from other repositories in our TensorFlow community (e.g. Keras, Keras-CV, and Keras-NLP).

For more information see: https://github.com/tensorflow/addons/issues/2807

  warnings.warn(
2023-09-27 16:20:49,055 - xirt.__main__ - INFO - xi params: parameter_examples//xirt_params_rp.yaml
2023-09-27 16:20:49,055 - xirt.__main__ - INFO - learning_params: parameter_examples//learning_params_training_cv.yaml
2023-09-27 16:20:49,056 - xirt.__main__ - INFO - peptides: DSS_xisearch_fdr_CSM50percent_minimal.csv
Traceback (most recent call last):
  File "d:\anaconda3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\anaconda3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "d:\anaconda3\Scripts\xirt.exe\__main__.py", line 7, in <module>
  File "d:\anaconda3\lib\site-packages\xirt\__main__.py", line 477, in main
    xirt_runner(args.in_peptides, args.out_dir, args.xirt_params, args.learning_params,
  File "d:\anaconda3\lib\site-packages\xirt\__main__.py", line 120, in xirt_runner
    if learning_params["train"]["mode"] == "train":
KeyError: 'train'

**Comment by gieses** [comment]
Thanks for your report. I am currently on vacation and won't be back before 9th of October. I am happy to look into your issue afterwards. How did you install xiRT with which python version? XiRT has not been updated for a while and the TFA msg is a bit cumbersome but I need to check it more carefully.

**Comment by wjlong0318** [comment]
The python version infor：
Python 3.10.9 | packaged by Anaconda, Inc. | (main, Mar 1 2023, 18:18:15) [MSC v.1916 64 bit (AMD64)] on win32



At 2023-09-27 17:21:01, "Sven Giese" ***@***.***> wrote:

Thanks for your report. I am currently on vacation and won't be back before 9th of October. I am happy to look into your issue afterwards. How did you install xiRT with which python version? XiRT has not been updated for a while and the TFA msg is a bit cumbersome but I need to check it more carefully.

**Comment by gieses** [comment]
I started to have a look at the environment and dependencies. It looks like it's going to be more work than thought. The used versions here are extremely outdated (py 3.7/3.8, tf 1.14). There wont be a quick solution but there will be one (migrating to tf >2.0). With keras 3.0 coming / TFA not being continued it wont last for long probably.

**Comment by gieses** [comment]
There is a WIP branch here with a conda env file [here](https://github.com/Rappsilber-Laboratory/xiRT/blob/upgrade_env/environment.yml). Install is possible with "conda env update -f environment.yml" (attention! it will create a new env using conda).

The training seems to work (tested only on windows, log attached with a smaller base config just for testing) but there is some issue remaining with the plotting with the updated versions. Models and results are stored just fine though. This uses Python 3.10.8, tf 2.10.

it's not perfect but might give you something to start with.

[xirt_logger.log](https://github.com/Rappsilber-Laboratory/xiRT/files/12910502/xirt_logger.log)
